// <auto-generated />
using System;
using DashboardAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DashboardAPI.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    [Migration("20250125170108_ExtendSeedData")]
    partial class ExtendSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DashboardAPI.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Performance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5936924-b385-4a11-8039-551886413ab0"),
                            DateOfBirth = new DateTime(2000, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Performance = 55
                        },
                        new
                        {
                            Id = new Guid("71dcdc95-a663-4b0b-b20c-0aa3fce11566"),
                            DateOfBirth = new DateTime(1999, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Performance = 72
                        },
                        new
                        {
                            Id = new Guid("d636d013-837e-49ee-baf4-1f2a6a135d7c"),
                            DateOfBirth = new DateTime(2001, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.johnson@example.com",
                            FirstName = "Emily",
                            LastName = "Johnson",
                            Performance = 20
                        },
                        new
                        {
                            Id = new Guid("8ff96f4e-b13e-4c0e-b75e-1e8a0f5a626b"),
                            DateOfBirth = new DateTime(1998, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.brown@example.com",
                            FirstName = "Michael",
                            LastName = "Brown",
                            Performance = 85
                        },
                        new
                        {
                            Id = new Guid("cd10cbc5-94ae-427d-8292-ad46a301cf21"),
                            DateOfBirth = new DateTime(2002, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophia.davis@example.com",
                            FirstName = "Sophia",
                            LastName = "Davis",
                            Performance = 95
                        },
                        new
                        {
                            Id = new Guid("bf0ff508-2da9-4788-beb6-a85efc595b20"),
                            DateOfBirth = new DateTime(2001, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "liam.wilson@example.com",
                            FirstName = "Liam",
                            LastName = "Wilson",
                            Performance = 37
                        },
                        new
                        {
                            Id = new Guid("492958de-86b7-4c3e-be39-6622a965b412"),
                            DateOfBirth = new DateTime(2003, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "olivia.taylor@example.com",
                            FirstName = "Olivia",
                            LastName = "Taylor",
                            Performance = 70
                        },
                        new
                        {
                            Id = new Guid("aa6f7354-97e2-49ab-bafe-8262c8ad70bd"),
                            DateOfBirth = new DateTime(1997, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "william.moore@example.com",
                            FirstName = "William",
                            LastName = "Moore",
                            Performance = 65
                        },
                        new
                        {
                            Id = new Guid("9fed3e16-c8e2-4091-aa33-4b1c0375400e"),
                            DateOfBirth = new DateTime(2000, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isabella.anderson@example.com",
                            FirstName = "Isabella",
                            LastName = "Anderson",
                            Performance = 89
                        },
                        new
                        {
                            Id = new Guid("e5ed13fc-482c-49ed-8d6c-9cb8651d9633"),
                            DateOfBirth = new DateTime(1999, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.harris@example.com",
                            FirstName = "James",
                            LastName = "Harris",
                            Performance = 87
                        },
                        new
                        {
                            Id = new Guid("133d5eb7-a7a9-4097-9a51-7ead12cc06e5"),
                            DateOfBirth = new DateTime(2002, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "charlotte.clark@example.com",
                            FirstName = "Charlotte",
                            LastName = "Clark",
                            Performance = 93
                        },
                        new
                        {
                            Id = new Guid("618bdbbb-86d0-4749-92de-878db697a9a9"),
                            DateOfBirth = new DateTime(1998, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "benjamin.martinez@example.com",
                            FirstName = "Benjamin",
                            LastName = "Martinez",
                            Performance = 52
                        },
                        new
                        {
                            Id = new Guid("331c952f-4d3b-4243-94de-4e3bdb3b24a3"),
                            DateOfBirth = new DateTime(2001, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amelia.garcia@example.com",
                            FirstName = "Amelia",
                            LastName = "Garcia",
                            Performance = 94
                        },
                        new
                        {
                            Id = new Guid("276b3000-721f-4b33-b038-38839697be18"),
                            DateOfBirth = new DateTime(1999, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elijah.rodriguez@example.com",
                            FirstName = "Elijah",
                            LastName = "Rodriguez",
                            Performance = 41
                        },
                        new
                        {
                            Id = new Guid("a71109d6-32c6-4b1e-a29a-d8838024aacb"),
                            DateOfBirth = new DateTime(2003, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mia.martins@example.com",
                            FirstName = "Mia",
                            LastName = "Martins",
                            Performance = 97
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
